// This file was auto-generated by prisma-generator-typescript-interfaces

export interface User {
  id: string;
  username: string;
  email: string;
  password: string;
  role_id: string;
  role?: Role;
  employee?: Employee | null;
  admin?: Admin | null;
  refreshToken: string | null;
}

export interface Role {
  id: string;
  name: string;
  users?: User[];
}

export interface Admin {
  id: string;
  user_id: string;
  user?: User;
}

export interface Employee {
  id: string;
  user_id: string;
  user?: User;
  bons_de_commande?: BonDeCommande[];
}

export interface BonDeCommande {
  id: string;
  created_at: Date;
  description: string;
  status: string;
  employee_id: string;
  employee?: Employee;
  commande_categories?: CommandeCategory[];
}

export interface CommandeCategory {
  id: string;
  bon_de_commande_id: string;
  bon_de_commande?: BonDeCommande;
  category_id: string;
  category?: Category;
  articles?: Article[];
}

export interface Category {
  id: string;
  name: string;
  description: string;
  commande_categories?: CommandeCategory[];
}

export interface Article {
  id: string;
  name: string;
  description: string;
  price: Decimal;
  commande_category_id: string;
  commande_category?: CommandeCategory;
}

type Decimal = { valueOf(): string };
