# backend/docker-compose.yml
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: erp_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: erp_db
      MYSQL_USER: erp_user
      MYSQL_PASSWORD: erp_pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
